AWSTemplateFormatVersion: "2010-09-09"
Description: Template to attach tags to the EC2 instance

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0022f774911c1d690
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: demo-ec2
        - Key: createdBy
          Value: DevOps Team
        - Key: Reason
          Value: Learning changesets concepts



