AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for s3 bucket     
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket    
    Properties:
      BucketName: vamsi-chunduru-27-05-22-demo